name: Format Documents

on: [push, pull_request]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Formater
        run: |
          npm install
          npm run prettier

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit-changes: "chore: format documents"
